ITP/ITP/Controllers/TLC_AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using ITP.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PasswordGenerator;

namespace ITP.Controllers
{
    public class TLC_AdminController : Controller
    {
        SqlCommand command;
        private static String connectionstring = "workstation id=Project.mssql.somee.com;packet size=4096;user id=donkavi2_SQLLogin_1;pwd=12345678;data source=Project.mssql.somee.com;persist security info=False;initial catalog=Project";
        SqlConnection connection = new SqlConnection(connectionstring);
        SqlDataReader reader;
        List<Customer> TestList = new List<Customer>();
        Customer test = null;
        private readonly AppDbContext DBob;
        private readonly IWebHostEnvironment _hostEnvironment;
        public TLC_AdminController(AppDbContext DB, IWebHostEnvironment hostEnvironment)
        {
            DBob = DB;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {

            return View();
        }

        //method that use to load the owner dashboard
        public IActionResult Owner_dashboard()
        {

            return View("Owner/Owner_dashboard");
        }



        //render the owner dashboard partial view1
        public IActionResult _dashboard()
        {
            string name = JsonConvert.DeserializeObject<String>(HttpContext.Session.GetString("nam"));

            string img = JsonConvert.DeserializeObject<String>(HttpContext.Session.GetString("Adminsession_img"));
            int ic = JsonConvert.DeserializeObject<int>(HttpContext.Session.GetString("ic"));
            int cc = JsonConvert.DeserializeObject<int>(HttpContext.Session.GetString("cc"));
            int oc = JsonConvert.DeserializeObject<int>(HttpContext.Session.GetString("oc"));
            int dc = JsonConvert.DeserializeObject<int>(HttpContext.Session.GetString("dc"));
            int fc = JsonConvert.DeserializeObject<int>(HttpContext.Session.GetString("fc"));
            int ec = JsonConvert.DeserializeObject<int>(HttpContext.Session.GetString("ec"));

            int sc = JsonConvert.DeserializeObject<int>(HttpContext.Session.GetString("sc"));
            int moc = JsonConvert.DeserializeObject<int>(HttpContext.Session.GetString("moc"));

            ViewBag.itemcount = ic;
            ViewBag.cuscount = cc;
            ViewBag.ocount = oc;
            ViewBag.dcount = dc;
            ViewBag.fcount = fc;
            ViewBag.mocount = moc;
            ViewBag.scount = sc;
            ViewBag.ecount = ec;
            DateTime now = DateTime.Now;
            string s = now.DayOfWeek.ToString();
            ViewBag.day = s;
            ViewBag.name = name;
            ViewBag.TerminoDaAvaliacao = now;

            return PartialView("Owner/_dashboard");
        }



        //render the owner dashboard partial view2
        public ActionResult CustomerList()
        {
            string img = JsonConvert.DeserializeObject<string>(HttpContext.Session.GetString("Adminsession_img"));
            command = new SqlCommand("select * from CustomerInfo", connection);
            // command.CommandType = System.Data.CommandType.TableDirect;
            connection.Open();
            reader = command.ExecuteReader();



            while (reader.Read())
            {
                test = new Customer();

                test.FirstName = reader["FirstName"].ToString();
                test.LastName = reader["LastName"].ToString();
                test.Email = reader["Email"].ToString();
                test.Address = reader["Address"].ToString();
                test.Cusid = int.Parse(reader["Cusid"].ToString());
                test.NIC = reader["NIC"].ToString();
                test.PhoneNumber = reader["PhoneNumber"].ToString();
                test.Image = reader["Image"].ToString();
                if (test.Image == null) {
                    test.Image = "default.png";
                }
                TestList.Add(test);
            }
            connection.Close();
            ViewBag.url = img;
            ViewBag.totalcustomer = TestList;
            return View("Owner/CustomerList");
        }




        //method for add new customer by admin modal
        [HttpPost]
        public ActionResult saveCustomer(Customer ob)
        {


            var pwd = new Password().IncludeLowercase().IncludeUppercase().LengthRequired(5);
            string result = pwd.Next();
            var uname = new Password().IncludeLowercase().LengthRequired(6);
            string runame = uname.Next();
            DateTime dt = DateTime.Now;
            DateTime dateOnly = dt.Date;
            ob.Joindate = dateOnly;
            ob.Username = runame;
            ob.Password = result;
            ob.ConfirmPassword = result;
            DBob.CustomerInfo.Add(ob);
            DBob.SaveChanges();


            string Themessage = @"<html>
                          <body>
                            <div style="" width: 500px; height: 620px; border: 6px solid DodgerBlue;position:relative; "">

                <img src = cid:myImageID style = "" width:150px;height:auto;position:relative;left:180px;margin-left:170px"">
        

                 <h4 style = ""position:relative;left:40px;font-family:Comic Sans MS;margin-left:60px;font-size:20px"" ><font color = ""DodgerBlue""> Hi </font>{name} we Created an Account for you </h4>
                  
                         <img src = cid:myImageID2 style = "" width:270px;height:250px;position:absolute;left:300px;border-radius:50%;margin-left:120px"">
                     
                            <h4 style = ""position:relative;left:90px;top:0px;margin-left:170px;font-size:20px""> Username = <font color = ""#9932CC"">{uname}</font> </h4>
                            <h4 style = ""position:relative;left:90px;top:0px;margin-left:170px;font-size:20px""> Password = <font color = ""#9932CC"">{pword}</font> </h4>
                          
                              <p style = ""font-size:20px;color:#FF7F50;position:relative;left:80px;top:0px;letter-spacing:5px;margin-left:70px"" >WELCOME TO TLC FAMILY </p>
                           

                           </div>
                            </body>
                            </html>";








            Themessage = Themessage.Replace("{uname}", runame);
            Themessage = Themessage.Replace("{pword}", result);
            Themessage = Themessage.Replace("{name}", ob.FirstName);
            string to = ob.Email; //To address    
            string from = "tlclifepartner2021@gmail.com"; //From address    
            MailMessage message = new MailMessage(from, to);
            AlternateView htmlView = AlternateView.CreateAlternateViewFromString(Themessage, null, "text/html");


            LinkedResource theEmailImage = new LinkedResource("wwwroot/Images/Customer/logo.png");
            theEmailImage.ContentId = "myImageID";
            htmlView.LinkedResources.Add(theEmailImage);

            LinkedResource theEmailImage2 = new LinkedResource("wwwroot/Images/Customer/rocket.gif");
            theEmailImage2.ContentId = "myImageID2";
            htmlView.LinkedResources.Add(theEmailImage2);

            message.AlternateViews.Add(htmlView);

            message.Subject = "Welcome To TLC Family";
            //message.Body = mailbody;
            message.BodyEncoding = Encoding.UTF8;
            message.IsBodyHtml = true;
            SmtpClient client = new SmtpClient("smtp.gmail.com", 587); //Gmail smtp    
            NetworkCredential MyCredentials = new NetworkCredential("tlclifepartner2021@gmail.com", "Tlc@2021");

            client.EnableSsl = true;
            client.UseDefaultCredentials = false;
            client.Credentials = MyCredentials;


            client.Send(message);


            return RedirectToAction("CustomerList");
        }

        //method for delete customer by admin modal
        [HttpPost]
        public ActionResult Delete_byadmin(int id)
        {
            command = new SqlCommand("delete CustomerInfo where Cusid = @id", connection);
            command.Parameters.Add("@id", SqlDbType.Int).Value = id;
            // command.CommandType = System.Data.CommandType.TableDirect;
            connection.Open();
            command.ExecuteNonQuery();
            return RedirectToAction("CustomerList");

        }

        //method for edit customer by admin modal popup
        public ActionResult Editcusdata(Customer ob)
        {

            command = new SqlCommand("update CustomerInfo set FirstName = @f,LastName = @l,Email = @e,Address = @a,NIC = @n,PhoneNumber = @pn where Cusid = @id", connection);
            command.Parameters.Add("@id", SqlDbType.Int).Value = ob.Cusid;
            command.Parameters.Add("@f", SqlDbType.NVarChar, 255).Value = ob.FirstName;
            command.Parameters.Add("@l", SqlDbType.NVarChar, 255).Value = ob.LastName;
            command.Parameters.Add("@e", SqlDbType.NVarChar, 200).Value = ob.Email;
            command.Parameters.Add("@a", SqlDbType.NVarChar, 100).Value = ob.Address;
            command.Parameters.Add("@n", SqlDbType.NVarChar, 100).Value = ob.NIC;
            command.Parameters.Add("@pn", SqlDbType.NVarChar, 100).Value = ob.PhoneNumber;
            connection.Open();
            command.ExecuteNonQuery();

            return RedirectToAction("CustomerList");


        }

        //method that use to implemet search function
        [HttpGet]
        public async Task<IActionResult> CustomerList2(string cusSearch) {
            ViewData["cusdetails"] = cusSearch;

ITP/ITP/Views/TLC_Admin/Index.cshtml
@{
    Layout = null;
}
@model ITP.Models.DropModel
<head>
    <style>
        .login-block {
            float: left;
            width: 100%;
            padding: 50px 0;
        }

        .banner-sec {
            background-image: url('/Images/Customer/admin_login_pic.svg');
            background-color: transparent !important;
            background-repeat: no-repeat;
            background-position: 100px 50px;
            background-size: contain;
            min-height: 500px;
            border-radius: 0 10px 10px 0;
            padding: 0;
        }

        .container {
            background: #fff;
            border-radius: 10px;
            box-shadow: 15px 20px 0px rgba(0,0,0,0.1);
            height: 500px;
        }

        .carousel-inner {
            border-radius: 0 10px 10px 0;
        }

        .carousel-caption {
            text-align: left;
            left: 5%;
        }

        .login-sec {
            padding: 50px 30px;
            position: relative;
        }

            .login-sec .copy-text {
                position: absolute;
                width: 80%;
                bottom: 20px;
                font-size: 13px;
                text-align: center;
            }

                .login-sec .copy-text i {
                    color: #536DFE;
                }

                .login-sec .copy-text a {
                    color: #536DFE;
                }

            .login-sec h2 {
                margin-bottom: 30px;
                font-weight: 800;
                font-size: 30px;
                color: #536DFE;
            }

                .login-sec h2:after {
                    content: " ";
                    width: 100px;
                    height: 5px;
                    background: #0099ff;
                    display: block;
                    margin-top: 20px;
                    border-radius: 3px;
                    margin-left: auto;
                    margin-right: auto
                }

        .btn-login {
            background: #536DFE;
            color: #fff;
            font-weight: 600;
        }

        .banner-text {
            width: 70%;
            position: absolute;
            bottom: 40px;
            padding-left: 20px;
        }

            .banner-text h2 {
                color: #fff;
                font-weight: 600;
            }

                .banner-text h2:after {
                    content: " ";
                    width: 100px;
                    height: 5px;
                    background: #FFF;
                    display: block;
                    margin-top: 20px;
                    border-radius: 3px;
                }

            .banner-text p {
                color: #fff;
            }

        body {
            background-image: linear-gradient(rgba(50,135,232,1),rgba(124,173,221,1)) !important;
        }

        option {
            margin-bottom: 7px;
        }
    </style>
</head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<section class="login-block">
    <div class="container">
        <div class="row">
            <div class="col-md-4 login-sec">
                <h2 class="text-center" style="color: black">Manager Login</h2>
                <form class="login-form" asp-action="ManagerLogin">
                    <input type ="hidden" id="t1" name="type1" />
                    <div class="form-group text-center">
                        @Html.DropDownListFor(m => m.Type, DropModel.GetSelectItems(),new {id = "id1" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1" class="">Username</label>
                        <input type="text" class="form-control" placeholder="" name="username" >

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="">Password</label>
                        <input type="password" class="form-control" placeholder="" name="password" onfocus="fun()">
                    </div>


                    <div class="form-check">
                        <label class="form-check-label">
                           
                        </label>
                        <button type="submit" class="btn  float-right" style="background-color:#0099ff !important;color:white" @*asp-action="CustomerList" asp-controller="TLC_Admin"*@ >Submit</button>
                    </div>

                </form>
                <div class="copy-text"> <i class="fa fa-heart"></i>  <a  asp-action="" asp-controller="" style ="color:#0099ff">Forget Password</a></div>
            </div>
            <div class="col-md-8 banner-sec">


            </div>
        </div>
    </div>
</section>
<script>

    var fun = function () {
        var d = $("#id1").val();
        $("#t1").val(d);
    }
</script>

ITP/ITP/Views/TLC_Admin/manager_edit.cshtml
@model ITP.Models.Admin

@{
    ViewData["Title"] = "manager_edit";
}

<h1>manager_edit</h1>

<h4>Admin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="editManager">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
               
                <input asp-for="Admin_ID" class="form-control" readonly />
               
            </div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone_Number" class="control-label"></label>
                <input asp-for="Phone_Number" class="form-control" />
                <span asp-validation-for="Phone_Number" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="NIC" class="control-label"></label>
                <input asp-for="NIC" class="form-control" />
                <span asp-validation-for="NIC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qualifications" class="control-label"></label>
                <input asp-for="Qualifications" class="form-control" />
                <span asp-validation-for="Qualifications" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>